nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/db":
      allow_origin: ["*"]
      # allow_headers: ['X-Custom-Auth']
      allow_headers: ["*"]
      allow_methods: ["GET"]
      max_age: 3600
    "^/db/new":
      allow_origin: ["*"]
      # allow_headers: ['X-Custom-Auth']
      allow_headers: ["*"]
      allow_methods: ["POST"]
      max_age: 3600
    "^/user/new":
      allow_origin: ["*"]
      # allow_headers: ['X-Custom-Auth']
      allow_headers: ["*"]
      allow_methods: ["POST"]
      max_age: 3600
    "^/database/.*?/recap":
      allow_origin: ["*"]
      # allow_headers: ['X-Custom-Auth']
      allow_headers: ["*"]
      allow_methods: ["GET"]
      max_age: 3600
    "^/database/dump":
      allow_origin: ["*"]
      allow_headers: ["*"]
      allow_methods: ["POST"]
      max_age: 3600
    "^/":
      allow_origin: ["*"]
      allow_headers: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      max_age: 3600
