
CREATE DATABASE IF NOT EXISTS apple;
USE apple;
CREATE TABLE IF NOT EXISTS client (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL
);

INSERT INTO client (name, email, address) VALUES
('John Doe', 'john@example.com', '123 Apple St'),
('Jane Smith', 'jane@example.com', '456 Orange Ave'),
('Alice Johnson', 'alice@example.com', '789 Banana Blvd'),
('Michael Brown', 'michael@example.com', '101 Cherry Ln'),
('Emily Davis', 'emily@example.com', '202 Grape Rd'),
('David Wilson', 'david@example.com', '303 Pine St'),
('Laura Garcia', 'laura@example.com', '404 Maple Ave'),
('Chris Martinez', 'chris@example.com', '505 Oak St'),
('Sarah Lee', 'sarah@example.com', '606 Elm St'),
('Daniel Harris', 'daniel@example.com', '707 Birch Blvd'),
('Jessica Clark', 'jessica@example.com', '808 Cedar Rd'),
('Matthew Lewis', 'matthew@example.com', '909 Fir St'),
('Olivia Walker', 'olivia@example.com', '1001 Walnut St'),
('Sophia Hall', 'sophia@example.com', '1112 Spruce Ave'),
('James Allen', 'james@example.com', '1213 Chestnut St'),
('Mia Young', 'mia@example.com', '1314 Sycamore Ln'),
('Noah King', 'noah@example.com', '1415 Poplar St'),
('Liam Wright', 'liam@example.com', '1516 Ash Rd'),
('Emma Scott', 'emma@example.com', '1617 Willow Blvd'),
('Ava Green', 'ava@example.com', '1718 Hickory Ave'),
('Isabella Adams', 'isabella@example.com', '1819 Hemlock St'),
('Ethan Nelson', 'ethan@example.com', '1920 Acacia Ln'),
('Lucas Carter', 'lucas@example.com', '2021 Fir Rd'),
('Amelia Mitchell', 'amelia@example.com', '2122 Juniper St'),
('Harper Perez', 'harper@example.com', '2223 Magnolia Ave'),
('Ella Roberts', 'ella@example.com', '2324 Redwood Blvd'),
('Scarlett Turner', 'scarlett@example.com', '2425 Sequoia St'),
('Grace Phillips', 'grace@example.com', '2526 Pecan Rd'),
('Chloe Campbell', 'chloe@example.com', '2627 Cottonwood Ln'),
('Lily Parker', 'lily@example.com', '2728 Dogwood St'),
('Aria Edwards', 'aria@example.com', '2829 Palm Ave'),
('Zoe Torres', 'zoe@example.com', '2930 Larch Blvd');

INSERT INTO product (name, weight, quantity) VALUES
('iPhone 13', 0.174, 50),
('MacBook Pro', 1.4, 30),
('iPad Air', 0.456, 20),
('Apple Watch', 0.032, 15),
('AirPods Pro', 0.005, 25),
('iMac', 5.0, 10),
('Mac Mini', 1.2, 12),
('Apple TV', 0.3, 40),
('HomePod', 2.5, 5),
('Apple Pencil', 0.2, 35),
('Beats Headphones', 0.25, 28),
('Magic Keyboard', 0.5, 22),
('AirTag', 0.1, 60),
('iPhone 12', 0.164, 45),
('MacBook Air', 1.3, 18),
('iPad Pro', 0.640, 14),
('Magic Mouse', 0.1, 33),
('Apple TV 4K', 0.3, 18),
('iPhone SE', 0.148, 37),
('iPod Touch', 0.088, 20),
('AirPods Max', 0.385, 16),
('iMac Pro', 5.0, 8),
('Mac Pro', 6.5, 4),
('Apple Care', 0.0, 100),
('Apple Gift Card', 0.0, 200),
('Lightning Cable', 0.05, 70),
('USB-C Adapter', 0.05, 75),
('AirPods 2nd Gen', 0.005, 30),
('iPhone 11', 0.194, 32),
('Apple Silicone Case', 0.1, 45),
('iPhone 13 Pro', 0.204, 38),
('iPad Mini', 0.300, 20),
('HomePod Mini', 0.8, 10),
('Apple Smart Keyboard', 0.6, 15),
('Magic Trackpad', 0.5, 22),
('Apple USB-C to USB Adapter', 0.05, 40),
('Apple Leather Wallet', 0.1, 20),
('AirPods Pro 2', 0.005, 25),
('iPad Pro 12.9', 0.682, 17),
('Apple Pencil 2nd Gen', 0.2, 30),
('iPhone 13 Mini', 0.140, 29),
('Apple Lightning to 3.5 mm Adapter', 0.01, 50),
('MacBook Air M1', 1.29, 19),
('Apple Watch SE', 0.035, 30),
('iPad Air 4', 0.500, 12),
('MacBook Pro 16', 2.0, 9),
('Apple AirPods Max', 0.385, 11),
('Magic Keyboard with Touch ID', 0.5, 23),
('Apple USB-C Power Adapter', 0.2, 60),
('Apple Watch Series 7', 0.050, 34),
('iPhone XR', 0.194, 32),
('iMac 24-inch', 4.5, 14),
('Apple Pencil 1st Gen', 0.2, 27),
('iPad 9th Gen', 0.490, 22);

CREATE DATABASE IF NOT EXISTS nike;
USE nike;

CREATE TABLE IF NOT EXISTS client (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL
);

INSERT INTO client (name, email, address) VALUES
('Michael Jordan', 'michael.jordan@example.com', '101 Nike St, Beaverton, OR'),
('LeBron James', 'lebron.james@example.com', '102 Nike St, Beaverton, OR'),
('Serena Williams', 'serena.williams@example.com', '103 Nike St, Beaverton, OR'),
('Cristiano Ronaldo', 'cristiano.ronaldo@example.com', '104 Nike St, Beaverton, OR'),
('Tiger Woods', 'tiger.woods@example.com', '105 Nike St, Beaverton, OR'),
('Kobe Bryant', 'kobe.bryant@example.com', '106 Nike St, Beaverton, OR'),
('Roger Federer', 'roger.federer@example.com', '107 Nike St, Beaverton, OR'),
('Rafael Nadal', 'rafael.nadal@example.com', '108 Nike St, Beaverton, OR'),
('Usain Bolt', 'usain.bolt@example.com', '109 Nike St, Beaverton, OR'),
('Neymar Jr.', 'neymar.jr@example.com', '110 Nike St, Beaverton, OR'),
('Tom Brady', 'tom.brady@example.com', '111 Nike St, Beaverton, OR'),
('Stephen Curry', 'stephen.curry@example.com', '112 Nike St, Beaverton, OR'),
('Mia Hamm', 'mia.hamm@example.com', '113 Nike St, Beaverton, OR'),
('Simone Biles', 'simone.biles@example.com', '114 Nike St, Beaverton, OR'),
('David Beckham', 'david.beckham@example.com', '115 Nike St, Beaverton, OR'),
('Peyton Manning', 'peyton.manning@example.com', '116 Nike St, Beaverton, OR'),
('Lionel Messi', 'lionel.messi@example.com', '117 Nike St, Beaverton, OR'),
('Virat Kohli', 'virat.kohli@example.com', '118 Nike St, Beaverton, OR'),
('Diana Taurasi', 'diana.taurasi@example.com', '119 Nike St, Beaverton, OR'),
('Babe Ruth', 'babe.ruth@example.com', '120 Nike St, Beaverton, OR'),
('Wayne Gretzky', 'wayne.gretzky@example.com', '121 Nike St, Beaverton, OR'),
('Danica Patrick', 'danica.patrick@example.com', '122 Nike St, Beaverton, OR'),
('Lindsey Vonn', 'lindsey.vonn@example.com', '123 Nike St, Beaverton, OR'),
('Carl Lewis', 'carl.lewis@example.com', '124 Nike St, Beaverton, OR'),
('Tony Hawk', 'tony.hawk@example.com', '125 Nike St, Beaverton, OR'),
('Alan Shearer', 'alan.shearer@example.com', '126 Nike St, Beaverton, OR'),
('Holly Holm', 'holly.holm@example.com', '127 Nike St, Beaverton, OR'),
('Zlatan Ibrahimovic', 'zlatan.ibrahimovic@example.com', '128 Nike St, Beaverton, OR'),
('Carmelo Anthony', 'carmelo.anthony@example.com', '129 Nike St, Beaverton, OR'),
('Klay Thompson', 'klay.thompson@example.com', '130 Nike St, Beaverton, OR'),
('Kevin Durant', 'kevin.durant@example.com', '131 Nike St, Beaverton, OR'),
('Alex Morgan', 'alex.morgan@example.com', '132 Nike St, Beaverton, OR'),
('Sofia Kenin', 'sofia.kenin@example.com', '133 Nike St, Beaverton, OR');

INSERT INTO product (name, weight, quantity) VALUES
('Air Max 270', 0.312, 50),
('Nike Air Force 1', 0.5, 70),
('Nike React Infinity', 0.400, 60),
('Zoom Pegasus 37', 0.300, 80),
('Air Zoom Structure 23', 0.350, 65),
('Nike Blazer Mid', 0.600, 55),
('Nike SB Dunk Low', 0.400, 40),
('Air Jordan 1', 0.500, 75),
('Nike Free RN 5.0', 0.275, 90),
('Nike Air Presto', 0.250, 72),
('Nike Air Max 90', 0.450, 65),
('Nike Downshifter 11', 0.280, 85),
('Nike Court Vision Low', 0.420, 50),
('Air Jordan 4', 0.600, 60),
('Nike Zoom Fly', 0.350, 77),
('Air Max 1', 0.400, 68),
('Nike Shox R4', 0.540, 42),
('Nike Air Huarache', 0.310, 80),
('Nike ACG Air Mowabb', 0.700, 32),
('Air Max 95', 0.550, 55),
('Nike SB Air Jordan 1', 0.490, 48),
('Nike Air VaporMax', 0.650, 30),
('Nike Air Max Fury', 0.450, 85),
('Air Jordan 3', 0.590, 40),
('Nike Air Zoom SuperRep', 0.400, 75),
('Nike Metcon 6', 0.720, 45),
('Nike React Element 55', 0.340, 70),
('Air Max 720', 0.640, 25),
('Nike Air Zoom Alphafly NEXT%', 0.280, 88),
('Nike Air Max 2090', 0.450, 60),
('Nike Air Max Tailwind 8', 0.560, 70),
('Nike Air Zoom Tempo NEXT%', 0.320, 82),
('Nike Air Max 2017', 0.580, 50),
('Nike Air Jordan 12', 0.620, 30),
('Nike Air Monarch IV', 0.550, 67),
('Nike Air Max 97', 0.500, 40),
('Nike Air Max Deluxe', 0.550, 55),
('Nike Air Force 1 Shadow', 0.500, 50),
('Nike Air Zoom Winflo 7', 0.290, 75),
('Nike Air Huarache Run', 0.320, 70),
('Nike Dunk High', 0.440, 60),
('Nike React Infinity Run', 0.400, 80),
('Nike Air Max 180', 0.520, 45),
('Nike Air Jordan 6', 0.620, 35);

CREATE DATABASE IF NOT EXISTS toyota;
USE toyota;

CREATE TABLE IF NOT EXISTS client (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL
);

INSERT INTO client (name, email, address) VALUES
('John Doe', 'john.doe@example.com', '201 Toyota Ave, Toyota City, Aichi'),
('Jane Smith', 'jane.smith@example.com', '202 Toyota Ave, Toyota City, Aichi'),
('Michael Brown', 'michael.brown@example.com', '203 Toyota Ave, Toyota City, Aichi'),
('Emily Davis', 'emily.davis@example.com', '204 Toyota Ave, Toyota City, Aichi'),
('Daniel Johnson', 'daniel.johnson@example.com', '205 Toyota Ave, Toyota City, Aichi'),
('Laura Wilson', 'laura.wilson@example.com', '206 Toyota Ave, Toyota City, Aichi'),
('Robert Martinez', 'robert.martinez@example.com', '207 Toyota Ave, Toyota City, Aichi'),
('Sarah Lee', 'sarah.lee@example.com', '208 Toyota Ave, Toyota City, Aichi'),
('James Garcia', 'james.garcia@example.com', '209 Toyota Ave, Toyota City, Aichi'),
('Linda Clark', 'linda.clark@example.com', '210 Toyota Ave, Toyota City, Aichi'),
('Thomas Lewis', 'thomas.lewis@example.com', '211 Toyota Ave, Toyota City, Aichi'),
('Sophia Walker', 'sophia.walker@example.com', '212 Toyota Ave, Toyota City, Aichi'),
('David Hall', 'david.hall@example.com', '213 Toyota Ave, Toyota City, Aichi'),
('Olivia Young', 'olivia.young@example.com', '214 Toyota Ave, Toyota City, Aichi'),
('Matthew King', 'matthew.king@example.com', '215 Toyota Ave, Toyota City, Aichi'),
('Ava Wright', 'ava.wright@example.com', '216 Toyota Ave, Toyota City, Aichi'),
('Jackson Scott', 'jackson.scott@example.com', '217 Toyota Ave, Toyota City, Aichi'),
('Mia Green', 'mia.green@example.com', '218 Toyota Ave, Toyota City, Aichi'),
('Liam Adams', 'liam.adams@example.com', '219 Toyota Ave, Toyota City, Aichi'),
('Isabella Nelson', 'isabella.nelson@example.com', '220 Toyota Ave, Toyota City, Aichi'),
('Ethan Carter', 'ethan.carter@example.com', '221 Toyota Ave, Toyota City, Aichi'),
('Charlotte Perez', 'charlotte.perez@example.com', '222 Toyota Ave, Toyota City, Aichi'),
('Alexander Roberts', 'alexander.roberts@example.com', '223 Toyota Ave, Toyota City, Aichi'),
('Amelia Turner', 'amelia.turner@example.com', '224 Toyota Ave, Toyota City, Aichi'),
('Henry Phillips', 'henry.phillips@example.com', '225 Toyota Ave, Toyota City, Aichi'),
('Ella Campbell', 'ella.campbell@example.com', '226 Toyota Ave, Toyota City, Aichi'),
('Noah Mitchell', 'noah.mitchell@example.com', '227 Toyota Ave, Toyota City, Aichi'),
('Avery Parker', 'avery.parker@example.com', '228 Toyota Ave, Toyota City, Aichi'),
('Sebastian Edwards', 'sebastian.edwards@example.com', '229 Toyota Ave, Toyota City, Aichi'),
('Sofia Collins', 'sofia.collins@example.com', '230 Toyota Ave, Toyota City, Aichi'),
('Jacob Stewart', 'jacob.stewart@example.com', '231 Toyota Ave, Toyota City, Aichi'),
('Harper Sanchez', 'harper.sanchez@example.com', '232 Toyota Ave, Toyota City, Aichi'),
('Lucas Morris', 'lucas.morris@example.com', '233 Toyota Ave, Toyota City, Aichi'),
('Zoe Rivera', 'zoe.rivera@example.com', '234 Toyota Ave, Toyota City, Aichi'),
('Samuel Cooper', 'samuel.cooper@example.com', '235 Toyota Ave, Toyota City, Aichi'),
('Victoria Reed', 'victoria.reed@example.com', '236 Toyota Ave, Toyota City, Aichi');

INSERT INTO product (name, weight, quantity) VALUES
('Toyota Camry', 1500.00, 30),
('Toyota Corolla', 1300.00, 40),
('Toyota RAV4', 1600.00, 35),
('Toyota Tacoma', 1800.00, 25),
('Toyota Prius', 1200.00, 45),
('Toyota Highlander', 1700.00, 28),
('Toyota 4Runner', 2000.00, 20),
('Toyota Sienna', 1900.00, 30),
('Toyota Avalon', 1600.00, 22),
('Toyota Supra', 1400.00, 50),
('Toyota Tundra', 2100.00, 15),
('Toyota Land Cruiser', 2400.00, 10),
('Toyota C-HR', 1300.00, 33),
('Toyota Mirai', 1400.00, 29),
('Toyota Sequoia', 2300.00, 18),
('Toyota Venza', 1600.00, 25),
('Toyota FJ Cruiser', 1700.00, 17),
('Toyota Highlander Hybrid', 1800.00, 24),
('Toyota Tacoma TRD Pro', 1850.00, 19),
('Toyota Camry Hybrid', 1450.00, 26),
('Toyota Corolla Hatchback', 1350.00, 31),
('Toyota RAV4 Hybrid', 1650.00, 34),
('Toyota Avalon Hybrid', 1550.00, 27),
('Toyota Crossover', 1400.00, 38),
('Toyota Supra GR', 1450.00, 32),
('Toyota Prius Prime', 1200.00, 42),
('Toyota Sienna Hybrid', 1950.00, 20),
('Toyota RAV4 Prime', 1700.00, 18),
('Toyota Yaris', 1100.00, 50),
('Toyota Hilux', 1800.00, 16),
('Toyota FJ Cruiser TRD', 2000.00, 12),
('Toyota Camry SE', 1500.00, 30),
('Toyota Corolla SE', 1300.00, 38),
('Toyota RAV4 XLE', 1650.00, 28),
('Toyota Tacoma SR5', 1750.00, 22),
('Toyota Avalon Touring', 1600.00, 26),
('Toyota Supra Turbo', 1400.00, 35),
('Toyota Tundra Limited', 2100.00, 14),
('Toyota 4Runner TRD', 2000.00, 19),
('Toyota Land Cruiser Heritage', 2400.00, 10),
('Toyota C-HR XLE', 1350.00, 27),
('Toyota Mirai XLE', 1450.00, 15),
('Toyota Highlander Limited', 1700.00, 23),
('Toyota Venza Limited', 1650.00, 20),
('Toyota Tundra TRD Pro', 2150.00, 12),
('Toyota Tacoma TRD Off-Road', 1850.00, 17),
('Toyota Camry XSE', 1500.00, 29),
('Toyota Corolla XSE', 1350.00, 31),
('Toyota RAV4 Adventure', 1700.00, 25),
('Toyota Prius c', 1100.00, 40),
('Toyota Avalon Limited', 1650.00, 14),
('Toyota Highlander Hybrid XLE', 1800.00, 19);

CREATE DATABASE IF NOT EXISTS samsung;
USE samsung;

CREATE DATABASE IF NOT EXISTS samsung;
USE samsung;

CREATE TABLE IF NOT EXISTS client (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    weight DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL
);

INSERT INTO client (name, email, address) VALUES
('Alice Johnson', 'alice.johnson@example.com', '301 Samsung St, Suwon, Gyeonggi'),
('Brian Wilson', 'brian.wilson@example.com', '302 Samsung St, Suwon, Gyeonggi'),
('Catherine Taylor', 'catherine.taylor@example.com', '303 Samsung St, Suwon, Gyeonggi'),
('David Anderson', 'david.anderson@example.com', '304 Samsung St, Suwon, Gyeonggi'),
('Emma Thomas', 'emma.thomas@example.com', '305 Samsung St, Suwon, Gyeonggi'),
('Frank Robinson', 'frank.robinson@example.com', '306 Samsung St, Suwon, Gyeonggi'),
('Grace Lee', 'grace.lee@example.com', '307 Samsung St, Suwon, Gyeonggi'),
('Henry Walker', 'henry.walker@example.com', '308 Samsung St, Suwon, Gyeonggi'),
('Irene Hall', 'irene.hall@example.com', '309 Samsung St, Suwon, Gyeonggi'),
('Jack Wright', 'jack.wright@example.com', '310 Samsung St, Suwon, Gyeonggi'),
('Katherine Scott', 'katherine.scott@example.com', '311 Samsung St, Suwon, Gyeonggi'),
('Leo Green', 'leo.green@example.com', '312 Samsung St, Suwon, Gyeonggi'),
('Mia Adams', 'mia.adams@example.com', '313 Samsung St, Suwon, Gyeonggi'),
('Nora Nelson', 'nora.nelson@example.com', '314 Samsung St, Suwon, Gyeonggi'),
('Oscar Carter', 'oscar.carter@example.com', '315 Samsung St, Suwon, Gyeonggi'),
('Paula Mitchell', 'paula.mitchell@example.com', '316 Samsung St, Suwon, Gyeonggi'),
('Quinn Perez', 'quinn.perez@example.com', '317 Samsung St, Suwon, Gyeonggi'),
('Ryan Edwards', 'ryan.edwards@example.com', '318 Samsung St, Suwon, Gyeonggi'),
('Sophia Turner', 'sophia.turner@example.com', '319 Samsung St, Suwon, Gyeonggi'),
('Thomas Phillips', 'thomas.phillips@example.com', '320 Samsung St, Suwon, Gyeonggi'),
('Uma Campbell', 'uma.campbell@example.com', '321 Samsung St, Suwon, Gyeonggi'),
('Victor Ramirez', 'victor.ramirez@example.com', '322 Samsung St, Suwon, Gyeonggi'),
('Wendy Lee', 'wendy.lee@example.com', '323 Samsung St, Suwon, Gyeonggi'),
('Xander Rodriguez', 'xander.rodriguez@example.com', '324 Samsung St, Suwon, Gyeonggi'),
('Yara Martinez', 'yara.martinez@example.com', '325 Samsung St, Suwon, Gyeonggi'),
('Zoe Gonzalez', 'zoe.gonzalez@example.com', '326 Samsung St, Suwon, Gyeonggi'),
('Albert Cruz', 'albert.cruz@example.com', '327 Samsung St, Suwon, Gyeonggi'),
('Bella Murphy', 'bella.murphy@example.com', '328 Samsung St, Suwon, Gyeonggi'),
('Carlos Cooper', 'carlos.cooper@example.com', '329 Samsung St, Suwon, Gyeonggi'),
('Diana Rogers', 'diana.rogers@example.com', '330 Samsung St, Suwon, Gyeonggi'),
('Ethan Reed', 'ethan.reed@example.com', '331 Samsung St, Suwon, Gyeonggi'),
('Fiona Long', 'fiona.long@example.com', '332 Samsung St, Suwon, Gyeonggi'),
('George Bailey', 'george.bailey@example.com', '333 Samsung St, Suwon, Gyeonggi'),
('Hannah Foster', 'hannah.foster@example.com', '334 Samsung St, Suwon, Gyeonggi');

INSERT INTO product (name, weight, quantity) VALUES
('Samsung Galaxy S22', 200.00, 50),
('Samsung Galaxy S22 Ultra', 230.00, 45),
('Samsung Galaxy Note 20', 220.00, 40),
('Samsung Galaxy Z Flip3', 180.00, 35),
('Samsung Galaxy Z Fold3', 300.00, 30),
('Samsung QLED TV', 2500.00, 20),
('Samsung Smart Fridge', 800.00, 15),
('Samsung Washing Machine', 600.00, 25),
('Samsung Dryer', 600.00, 20),
('Samsung Galaxy Buds Pro', 10.00, 100),
('Samsung Galaxy Watch 4', 30.00, 80),
('Samsung SSD 870 EVO', 70.00, 75),
('Samsung 980 PRO SSD', 80.00, 50),
('Samsung Portable SSD T7', 50.00, 60),
('Samsung Galaxy A52', 180.00, 55),
('Samsung Galaxy A72', 200.00, 50),
('Samsung Tab S7', 600.00, 25),
('Samsung Tab S7 FE', 550.00, 30),
('Samsung Galaxy A32', 160.00, 65),
('Samsung Galaxy A12', 150.00, 70),
('Samsung Smart Monitor', 1200.00, 15),
('Samsung Ultra HD Blu-ray Player', 500.00, 10),
('Samsung 32-Inch Monitor', 300.00, 20),
('Samsung 49-Inch Curved Monitor', 900.00, 12),
('Samsung 65-Inch TV', 1200.00, 18),
('Samsung 75-Inch TV', 1500.00, 15),
('Samsung Galaxy Tab A7', 250.00, 30),
('Samsung Galaxy J7', 160.00, 40),
('Samsung Galaxy M32', 180.00, 35),
('Samsung Gear S3', 50.00, 60),
('Samsung Galaxy Fit 2', 20.00, 100),
('Samsung Level U Pro', 30.00, 80),
('Samsung Bluetooth Speaker', 15.00, 90),
('Samsung Soundbar', 120.00, 55),
('Samsung SmartThings Hub', 60.00, 40),
('Samsung Wireless Charger', 20.00, 75),
('Samsung Travel Adapter', 10.00, 100),
('Samsung HDMI Cable', 5.00, 150),
('Samsung Galaxy A01', 150.00, 65),
('Samsung Galaxy A51', 190.00, 55),
('Samsung Galaxy Note 10', 210.00, 30),
('Samsung Galaxy J5', 160.00, 45),
('Samsung SmartThings Camera', 100.00, 25),
('Samsung SmartThings Motion Sensor', 30.00, 50),
('Samsung SmartThings Water Leak Sensor', 25.00, 60),
('Samsung SmartThings Button', 15.00, 80),
('Samsung SmartThings Doorbell', 40.00, 20),
('Samsung Family Hub Refrigerator', 900.00, 8),
('Samsung 860 EVO SSD', 70.00, 70),
('Samsung Wireless Earbuds', 10.00, 95),
('Samsung Galaxy A80', 200.00, 50),
('Samsung Galaxy Z Fold', 250.00, 15);


